version: '3'
services:
  pgsql:
    image: 'postgres:14'
    ports:
      - '${DB_PORT:-5432}:5432'
    env_file:
      - .env
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-melk_db}'
      POSTGRES_USER: '${DB_USERNAME:-root}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql_melk:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s
    networks:
      - net
volumes:
  pgsql_melk:
    driver: local
networks:
  net:
    driver: bridge